FROM bitnami/spark:3.2.1-debian-10-r24

COPY requirements.txt .

USER root

RUN apt-get clean  && \
    apt-get update && \
    apt-get install -y python3-pip && \
    pip3 install -r ./requirements.txt && \
    pip install tensorflow[and-cuda]